// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzz2dRrrcEt9c-f4R7VVucHoPVE3hX_0',
    appId: '1:549658336160:web:dada7d922528fa78c922c5',
    messagingSenderId: '549658336160',
    projectId: 'myhome-e1cc9',
    authDomain: 'myhome-e1cc9.firebaseapp.com',
    storageBucket: 'myhome-e1cc9.firebasestorage.app',
    measurementId: 'G-MXG9KQVNYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBLKNX7w5Pd09d0uUvnyEajg0NCD-glE',
    appId: '1:549658336160:android:6f59b4433cf49204c922c5',
    messagingSenderId: '549658336160',
    projectId: 'myhome-e1cc9',
    storageBucket: 'myhome-e1cc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAY38f_nINeGqSchAkjzG-qfllHKmJmeg',
    appId: '1:549658336160:ios:2c00a58106f4b024c922c5',
    messagingSenderId: '549658336160',
    projectId: 'myhome-e1cc9',
    storageBucket: 'myhome-e1cc9.firebasestorage.app',
    iosBundleId: 'com.example.myHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAY38f_nINeGqSchAkjzG-qfllHKmJmeg',
    appId: '1:549658336160:ios:2c00a58106f4b024c922c5',
    messagingSenderId: '549658336160',
    projectId: 'myhome-e1cc9',
    storageBucket: 'myhome-e1cc9.firebasestorage.app',
    iosBundleId: 'com.example.myHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtzz2dRrrcEt9c-f4R7VVucHoPVE3hX_0',
    appId: '1:549658336160:web:68a40e3f7adc0e62c922c5',
    messagingSenderId: '549658336160',
    projectId: 'myhome-e1cc9',
    authDomain: 'myhome-e1cc9.firebaseapp.com',
    storageBucket: 'myhome-e1cc9.firebasestorage.app',
    measurementId: 'G-9EWWEL2RJF',
  );
}
